version: 2

project_name: witr

builds:
  - id: witr
    main: ./cmd/witr
    binary: witr-{{ .Os }}-{{ .Arch }}
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.buildDate={{ .Date }}

archives:
  - id: witr
    formats:
    - 'binary'
    ids:
      - witr
    name_template: "{{ .Binary }}"

checksum:
  name_template: SHA256SUMS
  algorithm: sha256

nfpms:
  - id: witr
    package_name: witr
    file_name_template: "witr-{{ .Os }}-{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: Pranshu Parmar <pranshu.parmar@gmail.com>
    description: witr explains why a process or port is running by tracing its ancestry.
    homepage: https://github.com/pranshuparmar/witr
    license: Apache-2.0
    bindir: /usr/local/bin
    contents:
      - src: dist/*/witr-linux-{{ .Arch }}*
        dst: /usr/local/bin/witr
        file_info:
          mode: 0755
      - src: docs/cli/witr.1
        dst: /usr/share/man/man1/witr.1
        file_info:
          mode: 0644

release:
  github:
    owner: pranshuparmar
    name: witr
